rm      16n.tcl
rm      1Cbn.tcl
rm      26n.tcl
rm      32n.tcl
rm      3Can.tcl
rm      AnalysisSP1.tcl
rm      AxialFailureOfElement99.txt
rm      AxialSpHD_sample.tcl
rm      AxialSp_sample.tcl
rm      BuildRCrectSection.tcl
rm      BuildRCrectSection_IR.tcl
rm      CenterColAxialSpring.tcl
rm      CenterColSecFiber.tcl
rm      CenterColShearSpring.tcl
rm      CenterCol_basicModel_Cyclic.tcl
rm      CenterCol_basicModel_Dynamic.tcl
rm      CenterCol_basicModel_Pushover.tcl
rm      CheckingTripleFrictionPendulum_1DDynamics_ConstFriction.tcl
rm      CheckingTripleFrictionPendulum_1DDynamics_VariableFriction.tcl
rm      CheckingTripleFrictionPendulum_2DDynamic_ConstFriction.tcl
rm      CheckingTripleFrictionPendulum_2DDynamic_VariableFriction.tcl
rm      CheckingTripleFrictionPendulum_3DDynamic_ConstFriction.tcl
rm      CheckingTripleFrictionPendulum_3DDynamic_VariableFriction.tcl
rm      CheckingTripleFrictionPendulum_StaticCyclicPushover.tcl
rm      ConventionalColumn_Cyclic.tcl
rm      DisplayModel3D_IR.tcl
rm      DisplayPlane_IR.tcl
rm      Dispwall1-cg.tcl
rm      Dynamic.EQ.Uniform_LimitState.tcl
rm      EigenAnal_twoStoreyFrame.tcl
rm      EigenAnal_twoStoreyFrame1.tcl
rm      EigenAnal_twoStoreyShearFrame7.tcl
rm      EigenAnal_twoStoreyShearFrame8.tcl
rm      ElemPanelZone2D.tcl
rm      Ex1a.Canti2D.EQ.modif.tcl
rm      Ex1a.Canti2D.EQ.tcl
rm      Ex1a.Canti2D.Push.tcl
rm      Ex1b.Portal2D.EQ.tcl
rm      Ex1b.Portal2D.Push.tcl
rm      Ex7.Frame3D.analyze.Dynamic.EQ.Uniform.tcl
rm      Ex7.Frame3D.analyze.Dynamic.EQ.bidirect.tcl
rm      Ex7.Frame3D.analyze.Dynamic.EQ.multipleSupport.tcl
rm      Ex7.Frame3D.analyze.Dynamic.sine.multipleSupport.tcl
rm      Ex7.Frame3D.analyze.Static.Cycle.tcl
rm      Ex7.Frame3D.analyze.Static.Push.tcl
rm      Ex7.Frame3D.build.RCsec.tcl
rm      Ex7.Frame3D.build.Wsec.tcl
rm      Ex7.Frame3D.tcl
rm      Ex9.analyze.MomentCurvature2D.tcl
rm      Ex9.analyze.MomentCurvature3D.tcl
rm      Ex9a.build.UniaxialSection2D.tcl
rm      Ex9a.build.UniaxialSection3D.tcl
rm      Ex9b.build.WSection2D.tcl
rm      Ex9b.build.WSection3D.tcl
rm      Ex9c.build.RCSection.RectUnconfinedSymm2D.tcl
rm      Ex9c.build.RCSection.RectUnconfinedSymm3D.tcl
rm      Ex9d.build.RCSection.RectConfinedSymm2D.tcl
rm      Ex9d.build.RCSection.RectConfinedSymm3D.tcl
rm      Ex9e.build.RCSection.Rect2D.tcl
rm      Ex9e.build.RCSection.Rect3D.tcl
rm      Ex9f.build.RCSection.Circ2D.tcl
rm      Ex9f.build.RCSection.Circ3D.tcl
rm      Ex9g.build.HollowSection3D.tcl
rm      ExampleSP1.tcl
rm      Excavation.tcl
rm      FatigueExample.tcl
rm      Get_pyParam.tcl
rm      Get_qzParam.tcl
rm      Get_tzParam.tcl
rm      LibAnalysisDynamicParameters_IR.tcl
rm      LibMaterialsRC_IR.tcl
rm      LibUnits_IR.tcl
rm      Model_IR.tcl
rm      MRF_2Story_Concentrated.tcl
rm      MRF_2Story_Concentrated_10Oct2013.tcl
rm      MRF_2Story_Concentrated_PanelZone.tcl
rm      ModelSP1.tcl
rm      ModelingDiaphragms2D.tcl
rm      MomentCurvature2D.tcl
rm      MomentCurvature3D.tcl
rm      MultipleShearSpring_Sample.tcl
rm      MultipleShearSpring_input_X.tcl
rm      MultipleShearSpring_input_Y.tcl
rm      ProcRC.tcl
rm      ProcRC2.tcl
rm      ProcRCycDAns.tcl
rm      Pushover_concentrated.tcl
rm      Pushover_distributed.tcl
rm      Pushover_example.tcl
rm      RandomStrainHstory.tcl
rm      ReadRecord.tcl
rm      ReadSMDFile_IR.tcl
rm      RectangularRCsection2D.tcl
rm      RotLeaningCol.tcl
rm      RotPanelZone2D.tcl
rm      RotSect2DModIKModel.tcl
rm      RotSpring2DModIKModel.tcl
rm      SAWSZeroLength.tcl
rm      SingleCycle.tcl
rm      StaticBNWFpile.tcl
rm      Tags.tcl
rm      Test.tcl
rm      TestFPS2d_0.tcl
rm      TestFPS2d_1.tcl
rm      TestFPS2d_2.tcl
rm      TestFPS2d_3.tcl
rm      TestFPS2d_4.tcl
rm      TestFPS3d_0.tcl
rm      TestFPS3d_1.tcl
rm      TestFPS3d_2.tcl
rm      TestFPS3d_3.tcl
rm      TestFPS3d_4.tcl
rm      TestSlider2d_0.tcl
rm      TestSlider2d_1.tcl
rm      TestSlider2d_2.tcl
rm      TestSlider2d_3.tcl
rm      TestSlider2d_4.tcl
rm      TestSlider3d_0.tcl
rm      TestSlider3d_1.tcl
rm      TestSlider3d_2.tcl
rm      TestSlider3d_3.tcl
rm      TestSlider3d_4.tcl
rm      elasticPileSection.tcl
rm      peerRecords.txt

#       Motions/
#       data/
#       json/
#       a.sh
#       a.txt
#       b.txt
#       SCS052.AT2
#       SCS052.txt
#       SCS142.AT2
#       SCS142.txt
#       SCSUP.AT2
#       SCSUP.txt
#       TCU065-E.ATH
#       TCU065-N.ATH
#       TCU065-V.ATH
#       NR94cnp.tcl
#       NRHA_IR.tcl
#       PUL104.tcl
#       PUL194.tcl
#       StaticBNWFpile/StaticBNWFanalysis.zip
#       A10000.txt
#       MRF_Concentrated/Dynamic_example_10Oct2013.zip
#       MRF_PanelZone/MRF_PanelZone_example.zip
#       MRF_Pushover/Pushover_example.zip
#       Ex7/data/
#       Chopra-10.4/README-old.md
#       Chopra-10.4/README-older.md
#       Chopra-10.4/modes/
#       CFSWSWP/600px-26.png
#       CFSWSWP/600px-321.png
#       Chopra-10.4/172-Eigen analysis of a two-storey one-bay frame.html
#       BeamColumnJointExample/50-BeamColumnJointExample.html
#       ModelingDiaphragms2D/394-Modeling Diaphragms in 2D Models with Linear and Nonlinear Elements, Oct 2011.md
#       ModelingDiaphragms2D/DiaphragmsModeling.pdf
