model.glb: model.json
	 #python -m sees.frame.extrude  model.json --canvas gltf --vert 3 --show triads ; # -o model.glb
	 python -m sees  model.json --canvas gltf --vert 3 --show frame.axes --show frame.surface --style frame.surface.scale=10; # -o model.glb
